// Code generated by "stringer -type=CMD"; DO NOT EDIT.

package zero

import "strconv"

const _CMD_name = "ClientRequestSessionKeyClientRequestLogin"

var _CMD_index = [...]uint8{0, 23, 41}

func (i CMD) String() string {
	if i < 0 || i >= CMD(len(_CMD_index)-1) {
		return "CMD(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CMD_name[_CMD_index[i]:_CMD_index[i+1]]
}
